### ISSUE TITLE
Send any existing info on/examples of individual forest innovations to Alia

### ISSUE THREAD

**Issue by alia-salim** [18F/usfs-special-uses-prototype#25]

**Comment by christophermather** [comment]
Hi @alia-salim! Here's the doc I've been using to review forest special uses websites: https://docs.google.com/spreadsheets/d/19-hVvJ87W6clEj31a5dk8dRh9iKxT0z3KlaXhXezSNc/edit?gid=0#gid=0

It's a little bit of a mess, mostly because when I started I didn't know what I was looking for. As I went along, some themes emerged, which the [Appendix 3](https://docs.google.com/document/d/1VGbWeluqdELUvy59HoDxe9I3WdNkpNDfgYiLOz_eUJQ/edit#heading=h.vtq9r0sifwh9) in our recommendations does a good job summarizing.

Let me know if you'd like to walk through this at all.

**Comment by dluetger** [comment]
I added some more items to a [folder in Drive](https://drive.google.com/drive/folders/1LB5HpIC9CzZNw1n75SmT2KoiMxseahzP?usp=drive_link)

**Comment by dluetger** [comment]
@alia-salim Could you review? Do you feel like we've collected enough of these to close this?

**Comment by alia-salim** [comment]
@dluetger Ok by me to close -- can add anything else that comes in as we go along. Thanks for finding these!
