### ISSUE TITLE
Draft textual content for an initial permit application wizard

### ISSUE THREAD

**Issue by christophermather** [18F/usfs-special-uses-prototype#8]

**Comment by neilmb** [comment]
What is valuable about our mockup landing page?

- As a proponent I want to install fiber optic cable across FS lands so that I can provide internet service to unserved users.
- As a proponent I want to get a special use permit so that I can install fiber optic cable ...
- As a proponent, I want to submit a proposal for a permit so that I can get a permit.
 
- As a proponent, I **want to know what information is part of a proposal so that I can submit one.**

  - Plan of Development template
  - "this is what we are really looking for"
  - content design
  - visual design
  - web implementation

- As a proponent, I want to know who to send that information to so that I can submit a proposal.

"I don't know who to call or what to do?" Broadband website provides a "who to talk to". Some people reach out for "can we meet with you" or others have taken what is on the site and filled out the information so we can review it. They provide information but not the details we need. How do we get the right information?
 
- As a proponent, I want to track the progress of my proposal so that I can estimate when it will be approved
- As a proponent I want to estimate approval time so I can prepare for the installation and construction
 
- As a permit administrator, I want to know when proposals are submitted so that I can initiate screening
- As a permit administrator, I want to communicate efficiently with the proponent so that I can get the information needed for screening and approval

**Comment by christophermather** [comment]
Closing this in favor of #76 (content copied over in a comment in that epic)
