### ISSUE TITLE
Draft copy for a "Submit" page

### ISSUE THREAD

**Issue by christophermather** [18F/usfs-special-uses-prototype#91]
Following completion of #86, we'll move on to this and #92 

Once this is complete, alert @neilmb in #93 that his work is ready to begin.

**Comment by alia-salim** [comment]
@neilmb @dluetger

Working draft of the submit page (and a confirmation page) is [here](https://docs.google.com/document/d/1cyro-bvsv7U-EbtPSUlefmmZUh9ybZFOsMsZ5WplEyI/edit).

Based on a conversation with Neil, the copy describes a future state/complete product, rather than the partial prototype. (So, for example, it assumes that a user has uploaded supporting documents, vs. emailing them to a permit admin later.)

The copy on this page in particular would change a lot depending on the design and function of the page, so I'll plan to revisit it later. In the meantime, feedback/edits/questions welcome! Comments directly on the doc are easiest.
