### ISSUE TITLE
Draft copy for an "intro" page

### ISSUE THREAD

**Issue by christophermather** [18F/usfs-special-uses-prototype#92]
Following completion of #86, we'll move on to this and #91

**Comment by alia-salim** [comment]
@neilmb @dluetger 

Working draft of the intro page is [here](https://docs.google.com/document/d/1cyro-bvsv7U-EbtPSUlefmmZUh9ybZFOsMsZ5WplEyI/edit).

Based on a conversation with Neil, the intro copy describes a future state/complete product, rather than the partial prototype. (So, for example, it tells the user they will upload their supporting documents, vs. emailing them to a permit admin later.)

Feedback/edits/questions welcome! Comments directly on the doc are easiest.

**Comment by christophermather** [comment]
Marking "done" for our purposes.
